### ISSUE TITLE
Migratin to python 3

### ISSUE THREAD

**Issue by rtrepos** [vle-forge/pyvle#14]
Using python 3. I get this error :

/pub/src/vledev/pyvle/src/convert.cpp:89:18: error: ‘PyInstance_New’ was not declared in this scope
         result = PyInstance_New(class_, args, NULL);
                  ^~~~~~~~~~~~~~
/pub/src/vledev/pyvle/src/convert.cpp:89:18: note: suggested alternative: ‘PyAsyncGen_New’

Except I cannot find any documentation on PyAsyncGen_New for python 3.

**Comment by quesnel** [comment]
You want to bump PyVLE >= 2.1 with python3?

**Comment by rtrepos** [comment]
Yes I am trying to do this.

**Comment by rtrepos** [comment]
I did not manage to use python3 on ubuntu 18.04. 
I managed to link pyvle.so libpython3 but not to link it to libboost_python-py36 (only py27 which lead to a link error).
So, I will try to update vle >= 2.1 for python2.7 only.

**Comment by rtrepos** [comment]
FindBoost is able to find boost python for a specific version of python(27 or 36), starting from cmake version 3.11
