### ISSUE TITLE
windows compilation fails to load and use Vpz file

### ISSUE THREAD

**Issue by ynedelec3** [vle-forge/pyvle#17]
Hi,
I tried to use pyvle successfully compiled on windows with Boost 1 70 and gcc/g++ shipped with VLE 2.0.2. Import in python 2.7.16 works well too, but opening a vpz file buigs and leads to a fatal error when calling listConditions. Different formats where tested for vpz file (unix, dos, utf-8 with and without BOM...) which is successfully created and managed by VLE 2.0.2 gui on Windows.

Where can be the error in Vpz reading ? A failure in xml parsing ? VLE dll used in compilation comes with VLE 2.0.2 application...

Thanks for any clue.

Python screen capture :

Microsoft Windows [version 10.0.18362.720]
(c) 2019 Microsoft Corporation. Tous droits réservés.

Python 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:30:55) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvle
>>> from pyvle import Vle
>>> dir(pyvle.Vle)
['__doc__', '__init__', '__module__', 'addBooleanCondition', 'addEventView', 'addFinishView', 'addIntegerCondition', 'addMapCondition', 'addMatrixCondition', 'addObservable', 'addObservablePort', 'addRealCondition', 'addSetCondition', 'addStringCondition', 'addTableCondition', 'addTimedView', 'addTupleCondition', 'addValueCondition', 'addXMLCondition', 'clearConditionPort', 'clearObservables', 'createCondition', 'delConditionValue', 'delObservable', 'delObservablePort', 'existObservable', 'export', 'exportManager', 'getBegin', 'getConditionPortValue', 'getConditionPortValues', 'getConditionSetValue', 'getConditionValueType', 'getDuration', 'getDynamicLanguage', 'getDynamicLibrary', 'getDynamicModel', 'getDynamicName', 'getExperimentName', 'getObservableName', 'getObservablePortAttachedViews', 'getObservablePortName', 'getOutputLocation', 'getOutputPlugin', 'getViewData', 'getViewName', 'getViewOutput', 'getViewTimeStep', 'getViewType', 'hasObservableView', 'isObservablesEmpty', 'isPermanentObservable', 'listAtomicModelConditions', 'listConditionPorts', 'listConditions', 'listDynamicConditions', 'listDynamicModels', 'listDynamicObservables', 'listDynamics', 'listObservablePorts', 'listObservables', 'listOutputs', 'listViews', 'listViewsEntries', 'run', 'runCombination', 'runManager', 'runManagerCluster', 'runManagerClusterMatrix', 'runManagerMatrix', 'runManagerThread', 'runManagerThreadMatrix', 'runMatrix', 'save', 'setBegin', 'setConditionPortValue', 'setConditionValue', 'setDuration', 'setDynamicLanguage', 'setDynamicLibrary', 'setDynamicModel', 'setName', 'setNormalMode', 'setOutputPlugin', 'setPackageMode', 'setPermanentObservable', 'setViewData', 'setViewName', 'setViewTimeStep', 'setViewType', 'traceRunError']
>>> f = Vle("NewVpz.vpz")
debug: Environment
debug: =::=::\
debug: =C:=C:\Users\icido\vle\projets\tuto1\lotkavolterra\exp
debug: =F:=F:\
debug: ALLUSERSPROFILE=C:\ProgramData
debug: APPDATA=C:\Users\icido\AppData\Roaming
debug: CMAKE_INCLUDE_PATH=D:\NedelecDev\32bits\python27\include;D:\NedelecDev\32bits\boost_1_72_0;C:\Program Files (x86)\VLE_2_0_2\include\vle-2.0
debug: CMAKE_MODULE_PATH=C:\Program Files (x86)\VLE_2_0_2\bin
debug: CommonProgramFiles=C:\Program Files (x86)\Common Files
debug: CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
debug: CommonProgramW6432=C:\Program Files\Common Files
debug: COMPUTERNAME=LAPTOP-IDA4G5R0
debug: ComSpec=C:\WINDOWS\system32\cmd.exe
debug: DriverData=C:\Windows\System32\Drivers\DriverData
debug: FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
debug: FPS_BROWSER_USER_PROFILE_STRING=Default
debug: GameFirst=C:\Program Files (x86)\ASUS\GameFirst V\
debug: GDAL_DATA=C:\Program Files\PostgreSQL\12\gdal-data
debug: HOMEDRIVE=C:
debug: HOMEPATH=\Users\icido
debug: LOCALAPPDATA=C:\Users\icido\AppData\Local
debug: LOGONSERVER=\\LAPTOP-IDA4G5R0
debug: MOZ_PLUGIN_PATH=C:\Program Files (x86)\Foxit Software\Foxit Reader\plugins\
debug: NUMBER_OF_PROCESSORS=12
debug: OneDrive=C:\Users\icido\OneDrive
debug: OS=Windows_NT
debug: PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
debug: PKG_CONFIG_PATH=C:\Program Files (x86)\VLE_2_0_2\lib\pkgconfig
debug: POSTGIS_ENABLE_OUTDB_RASTERS=1
debug: POSTGIS_GDAL_ENABLED_DRIVERS=GTiff PNG JPEG GIF XYZ DTED USGSDEM AAIGrid
debug: PROCESSOR_ARCHITECTURE=x86
debug: PROCESSOR_ARCHITEW6432=AMD64
debug: PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
debug: PROCESSOR_LEVEL=6
debug: PROCESSOR_REVISION=9e0a
debug: ProgramData=C:\ProgramData
debug: ProgramFiles=C:\Program Files (x86)
debug: ProgramFiles(x86)=C:\Program Files (x86)
debug: ProgramW6432=C:\Program Files
debug: PROMPT=$P$G
debug: PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
debug: PUBLIC=C:\Users\Public
debug: SESSIONNAME=Console
debug: SystemDrive=C:
debug: SystemRoot=C:\WINDOWS
debug: TEMP=C:\Users\icido\AppData\Local\Temp
debug: TMP=C:\Users\icido\AppData\Local\Temp
debug: USERDOMAIN=LAPTOP-IDA4G5R0
debug: USERDOMAIN_ROAMINGPROFILE=LAPTOP-IDA4G5R0
debug: USERNAME=icido
debug: USERPROFILE=C:\Users\icido
debug: VLE_BASEPATH=C:\Program Files (x86)\VLE_2_0_2
debug: windir=C:\WINDOWS
>>> print(f)
<pyvle.Vle instance at 0x03185328>
>>> f.listConditions()
Assertion failed!

Program: D:\NedelecDev\32bits\python27\python.exe
File: D:\NedelecDev\pyvle-master2.0\src\pyvle.cpp, Line 544

Expression: file

And Python exits there...

**Comment by ynedelec3** [comment]
Different syntax for vpz file location were tested, in this example vpz file is in the dirctory used for python call...

**Comment by rtrepos** [comment]
Hi ynedelec3,
Thanks for trying this ! And I think you are doing great. But..

First, the python port was never tested on windows before.
And furthermore, this version is an old one which is not supported anymore (and we did not update it).
Unfortunatey, the new version of pyvle (based on pybind11) is developped for the development version of vle (only on github) for which there is no Windows installer yet. And it is again tested only on linux systems.

Is there any chance that you use other tools to simulate your vle model ?

**Comment by ynedelec3** [comment]
Thanks for your quick answer. Using pyvle is not an absolute priority for me it was a potential need so I will keep this pending presently and work with VLE gui will do.
Anyway if you want future Windows guinea pig I may be one of these...

**Comment by quesnel** [comment]
Hi,

On mar. 14 avril 20, ynedelec3 wrote:
> I tried to use pyvle successfully compiled on windows with Boost 1 70
> and gcc/g++ shipped with VLE 2.0.2. Import in python 2.7.16 works well
> too, but opening a vpz file buigs and leads to a fatal error when
> calling listConditions. Different formats where tested for vpz file
> (unix, dos, utf-8 with and without BOM...) which is successfully
> created and managed by VLE 2.0.2 gui on Windows.
> 
> Where can be the error in Vpz reading ? A failure in xml parsing ? VLE
> dll used in compilation comes with VLE 2.0.2 application...

PyVLE use the same XML parser as VLE/GVLE. This is not a failure in xml
parsing. May be a path error?

> Python 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:30:55) [MSC v.1500 32 bit (Intel)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import pyvle
> >>> from pyvle import Vle
> >>> dir(pyvle.Vle)
> ['__doc__', '__init__', '__module__', 'addBooleanCondition', 'addEventView', 'addFinishView', 'addIntegerCondition', 'addMapCondition', 'addMatrixCondition', 'addObservable', 'addObservablePort', 'addRealCondition', 'addSetCondition', 'addStringCondition', 'addTableCondition', 'addTimedView', 'addTupleCondition', 'addValueCondition', 'addXMLCondition', 'clearConditionPort', 'clearObservables', 'createCondition', 'delConditionValue', 'delObservable', 'delObservablePort', 'existObservable', 'export', 'exportManager', 'getBegin', 'getConditionPortValue', 'getConditionPortValues', 'getConditionSetValue', 'getConditionValueType', 'getDuration', 'getDynamicLanguage', 'getDynamicLibrary', 'getDynamicModel', 'getDynamicName', 'getExperimentName', 'getObservableName', 'getObservablePortAttachedViews', 'getObservablePortName', 'getOutputLocation', 'getOutputPlugin', 'getViewData', 'getViewName', 'getViewOutput', 'getViewTimeStep', 'getViewType', 'hasObservableView', 'isObservablesEmpty', 'isPermanentObservable', 'listAtomicModelConditions', 'listConditionPorts', 'listConditions', 'listDynamicConditions', 'listDynamicModels', 'listDynamicObservables', 'listDynamics', 'listObservablePorts', 'listObservables', 'listOutputs', 'listViews', 'listViewsEntries', 'run', 'runCombination', 'runManager', 'runManagerCluster', 'runManagerClusterMatrix', 'runManagerMatrix', 'runManagerThread', 'runManagerThreadMatrix', 'runMatrix', 'save', 'setBegin', 'setConditionPortValue', 'setConditionValue', 'setDuration', 'setDynamicLanguage', 'setDynamicLibrary', 'setDynamicModel', 'setName', 'setNormalMode', 'setOutputPlugin', 'setPackageMode', 'setPermanentObservable', 'setViewData', 'setViewName', 'setViewTimeStep', 'setViewType', 'traceRunError']
> >>> f = Vle("NewVpz.vpz")
> >>> print(f)
> >>> f.listConditions()
> Assertion failed!

Is the file NewVpz.vpz exists in the current path? Can you try with a
full absolute path and/or with a package name?

f = Vle("c://NewVpz.vpz")

f = Vle("vle.adaptative-qess.examples", "lotkavolterra.vpz")

**Comment by ynedelec3** [comment]
Hi,
I think I have tested all filename formats -)
A test with a package name value does not operate either.

I found a strange thing : 

In the Vle Class **__init__** function, **pyvle.py** line 85
filename matches the basestring case so that line 86 is executed and libvle.open_pkg is called, but in this case package name is ''

Function **pyvle_open_pkg** in **pyvle.cpp** line 55 is then called and I guess make_context (line 64) prints the "debug: ..." like lines on console (as far as I could see in vle/src/utils sources)

Variable **filepath** in this function should be the path to access vpz file but it cannot be set from an undefined package (filename is used in "std::string filepath = pack.getExpFile(filename);" line 66.

Would a function like pyvle_open_file distinct from pyvle_open_pkg be a solution ?

Anyway I cannot explain a similar failure when a package name is given, I tested also vpz filename twice...

I didn't try any change in cpp files presently, If necessary I may test minor changes ...

**Comment by ynedelec3** [comment]
It seems that an open_file function was removed, so a package needs to be given. Which package is associated to a custom vpz file ? Is it the project directory ?

**Comment by ynedelec3** [comment]
It worked with syntax ('filename.vpz', 'projectname')
where 'projectname' is the project as created built and installed with the gvle interface.
Great moment -)
