### ISSUE TITLE
vpz without any view in storage mode

### ISSUE THREAD

**Issue by rousse** [vle-forge/pyvle#9]
Execution:
> exp = pyvle.Vle( "smartgardener.vpz", "vle.examples" )
> exp.run()
Segmentation fault

is not ok, whereas

> exp = pyvle.Vle( "smartgardener.vpz", "vle.examples" )
> exp.setOutputPlugin("view","","local","storage","vle.output")
> exp.run()

is ok

**Comment by quesnel** [comment]
Fixed in #11
